apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dht4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dht4
    app.kubernetes.io/part-of: my-app1
  name: devfile-sample-dht4
  namespace: ktsao-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-dht4
status:
  loadBalancer: {}
